### ISSUE TITLE
What is the api?

### ISSUE THREAD

**Issue by yerbol89** [m1ky91/qa-rest-api#1]
Hi bro. How are you? 
This API to create applications on Q2A? Can you describe the details of the plugin. Thanks!

**Comment by m1ky91** [comment]
Hi, 

the plugin will expose the data of your q2a site (users,  questions,  answers,  categories and tags) via a REST Application Programming Interface (API).  For example you can load a list of all the questions making a http request. Since the API is based on REST principles, it's very easy to write and test applications. You can use your browser to access URLs, and you can use pretty much any HTTP client in any programming language to interact with the API. The plugin is new but I will try to improve with time its functionality. These days I will describe the plugin in the readme file. 

Regards

**Comment by yerbol89** [comment]
@m1ky91 cool. Thanks. Good luck.
